# Numpy

### Creando Arrays

In [1]:
import numpy as np

In [9]:
a=np.array([1,2,"a"])
n=np.array((1,2,3))
b=np.array([[1,3,4]])
c=np.array(5)
print(a)
print(n)
print(b)
print(c)
print(a.ndim)
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(c))

['1' '2' 'a']
[1 2 3]
[[1 3 4]]
5
1
1
2
0


In [11]:
c=np.array([(1,2,3),(4,5,6)])
j=np.array([[1,2,3],[4,5,6]])
print(c)
print(j)
print(np.ndim(j))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
2


In [3]:
d=np.array((1,2,3))
print(d)

[1 2 3]


In [5]:
d=np.array([1,2,3],ndmin=3)
print(d)

[[[1 2 3]]]


In [18]:
e=np.arange(2,9,100)
print(e)

[2]


In [10]:
f=np.arange(9)
print(f)

[0 1 2 3 4 5 6 7 8]


In [22]:
g=np.linspace(1,5,4)
print(g)

[1.         2.33333333 3.66666667 5.        ]


In [14]:
h=np.random.random((2,2))
print(h)

[[0.79562769 0.943081  ]
 [0.40094535 0.13831423]]


In [21]:
h=np.random.random(2)
print(h)

[0.79891278 0.44781525]


In [20]:
i=np.random.randint(5)
print(i)

2


In [26]:
i=np.random.randint(5,size=(2,3))
print(i)

[[1 2 4]
 [4 3 1]]


In [30]:
i=np.random.randint(5,(7,8,9))
print(i)

[6 6 7]


In [32]:
k=np.random.rand(2,4)
print(k)

[[0.43170965 0.40580755 0.25336787 0.23236872]
 [0.17846549 0.07808056 0.31675582 0.7198344 ]]


In [39]:
l=np.random.choice(4)
print(l)

1


In [43]:
l=np.random.choice(4,7)
print(l)

[3 1 1 1 3 2 1]


In [44]:
l=np.random.choice(4,(7,1))
print(l)

[[0]
 [2]
 [3]
 [3]
 [3]
 [2]
 [0]]


### Inspecting

In [45]:
h=np.random.random((2,3))
print(h)

[[0.44829312 0.8623487  0.68822232]
 [0.50691844 0.60370618 0.94180955]]


In [46]:
print(np.shape(h))

(2, 3)


In [47]:
print(np.size(h))

6


In [48]:
print(len(h))

2


In [49]:
print(np.ndim(h))

2


In [58]:
k=np.array([3,np.nan ,5])
print(np.isnan(k))

[False  True False]


In [24]:
S=np.array([1,2,2,2,2,3,3,5,6,6])
print(np.unique(S))

[1 2 3 5 6]


In [25]:
print(np.where(S==2))

(array([1, 2, 3, 4], dtype=int64),)


In [16]:
A=np.array([('z','b','a','t','m')])
print(np.sort(A))

[['a' 'b' 'm' 't' 'z']]


### Statistics

In [26]:
h=np.random.random((2,3))
print(h)

[[0.07919193 0.00619694 0.09709848]
 [0.37162308 0.42866891 0.55126027]]


In [27]:
print(np.sum(h))

1.5340396181454692


In [28]:
print(np.min(h))

0.006196939396575396


In [29]:
print(np.mean(h))

0.25567326969091153


In [30]:
print(np.cumsum(h))

[0.07919193 0.08538887 0.18248735 0.55411043 0.98277934 1.53403962]


### Modify

In [34]:
i=np.random.randint(5,size=(2,3))
print(i)

[[4 2 1]
 [2 2 3]]


In [38]:
j=np.reshape(i,(3,2))
print(j)

[[4 2]
 [1 2]
 [2 3]]


In [39]:
m=np.transpose(i)
print(m)

[[4 2]
 [2 2]
 [1 3]]


In [9]:
i=np.random.randint(5,size=(2,3))
print(i.size)

6


In [40]:
n=np.array([(1,2),(3,4)])
print(n)
print(n.shape)
print(n.size)

[[1 2]
 [3 4]]
(2, 2)
4


In [25]:
print(n.reshape(1,4))

[[1 2 3 4]]


In [30]:
o=np.flatten(n)
print(o)

[1 2 3 4]


### Agregate/Removing/Concatenate

In [8]:
n=np.array([(1,2),(3,4)])
print (n)
m=np.append(n,[(5,2),(7,8)],axis=1)# te lo flatten si no indicas el axis
print(m)

[[1 2]
 [3 4]]
[[1 2 5 2]
 [3 4 7 8]]


In [65]:
n=np.array([(1,2),(3,4)])
print (n)
m=np.append(n,[(7,8)])
print(m)

[[1 2]
 [3 4]]
[1 2 3 4 7 8]


In [73]:
n=np.array([(1,2),(3,4)])
print (n)
m=np.append(n,[(5,4),(9,7)],axis=0)# te append arrays con arrays tiene que tener la misma dimensión
print(m)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 4]
 [9 7]]


In [76]:
n=np.array([(1,2),(3,4)])
print (n)
p=np.insert(n,3,8)#axis=0 lo flatten
print(p)

[[1 2]
 [3 4]]
[1 2 3 8 4]


In [51]:
n=np.array([(1,2),(3,4)])
print (n)
p=np.insert(n,1,8,axis=0)
print(p)

[[1 2]
 [3 4]]
[[1 2]
 [8 8]
 [3 4]]


In [85]:
print(p)
q=np.delete(p,1,axis=0)
print(q)

[[1 8 2]
 [3 8 4]]
[[1 8 2]]


In [53]:
print(p)
q=np.delete(p,1,axis=1)
print(q)

[[1 2]
 [8 8]
 [3 4]]
[[1]
 [8]
 [3]]


In [54]:
print(q)

[[1]
 [8]
 [3]]


In [56]:
w=np.tile(q,2)
print(w)

[[1 1]
 [8 8]
 [3 3]]


In [57]:
print(q)
z=np.tile(q,(2,3))
print(z)

[[1]
 [8]
 [3]]
[[1 1 1]
 [8 8 8]
 [3 3 3]
 [1 1 1]
 [8 8 8]
 [3 3 3]]


In [59]:
C=np.array([[1, 2], [3, 4]])
D=np.array([[5, 6], [7, 8]])
E=np.concatenate((C,D), axis=1)
print(C)
print(D)
print(E)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [7]:
C=np.array([[1, 2], [3, 4]])
D=np.array([[5, 6], [7, 8]])
E=np.concatenate((C,D), axis=1)

print(E)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
C=np.array([1, 2,3])
D=np.array([5, 6,7])
E=np.array([9,6,4])
H=np.stack((C,D,E),axis=0)
print(H)

[[1 2 3]
 [5 6 7]
 [9 6 4]]


In [19]:
C=np.array([1, 2,3])
D=np.array([5, 6,7])
E=np.array([9,6,4])
H=np.stack((C,D,E),axis=1)
print(H)

[[1 5 9]
 [2 6 6]
 [3 7 4]]


In [21]:
C=np.array([1, 2,3])
D=np.array([5, 6,7])
E=np.array([9,6,4])
H=np.stack((C,E,D),axis=0)
print(H)

[[1 2 3]
 [9 6 4]
 [5 6 7]]


In [23]:
C=np.array([[1, 2], [3, 4]])
D=np.array([[5, 6], [7, 8]])
H=np.stack((C,D),axis=0)
print(H)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
C=np.array([[1, 2], [3, 4]])
D=np.array([[5, 6], [7, 8]])
H=np.stack((C,D),axis=1)
print(H)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### Selecting/Slicing

In [61]:
A=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print(A[2])

[7 8 9]


In [96]:
B=np.array([8,9,4])
print(B)
print(B[2])

[8 9 4]
4


In [64]:
A=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(A)
print(A[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [101]:
print(A[:2])

[[1 2 3]
 [4 5 6]]


In [66]:
print(A[2,:2])

[7 8]


In [68]:
print(A[1:-1])

[[4 5 6]]


In [4]:
print(A[:3:2,1:2])

[[2]
 [8]]


### Split

In [2]:
L=np.array([1,2,3,4,5,6])
print(L)
B=np.split(L,2)
print(B)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


In [31]:
L=np.array([1,2,3,4,5,6])
print(L)
B=np.array_split(L,4)
#print(B)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Operations/Ufuncs/Broadcasting

In [3]:
G=np.array([(1,2),(3,4)])
K=np.array([(5,6),(1,1)])
F=np.array(G+K)
print(F)

[[6 8]
 [4 5]]


In [4]:
print(np.add(G,3))

[[4 5]
 [6 7]]


In [7]:
#print(np.dot(G,K))

[[ 7  8]
 [19 22]]


In [9]:
V=np.array([(3,2,6),(1,0,1)])
#print(np.dot(G,V))

[[ 5  2  8]
 [13  6 22]]


### Filters

In [10]:
M=np.array([5,2,4,6,7,8])
q=M>4
Z=M[q]
#print(Z)

[5 6 7 8]


In [11]:
M[2]=28
#print(M)

[ 5  2 28  6  7  8]
